{
 "title": "Choria Server Provisioner",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": "choria_provisioner_discover_cycles"
   }
  ]
 },
 "panels": [
  {
   "title": "Nodes Provisioned / Hour",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 20, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(choria_provisioner_provisioned{site=\"${instance}\"}[1h]))"
    }
   ]
  },
  {
   "title": "Busy Workers",
   "type": "singlestat",
   "description": "How many of the available workers are provisioning nodes",
   "gridPos": { "h": 4, "w": 2, "x": 20, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "choria_provisioner_busy_workers{site=\"${instance}\"}"
    }
   ]
  },
  {
   "title": "Circuit Breaker",
   "type": "singlestat",
   "description": "If the backplane paused execution",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "choria_provisioner_paused{site=~\"${instance}\"}"
    }
   ]
  },
  { "title": "Processing Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Discovery",
   "type": "graph",
   "description": "How many discovery cycles were ran and how many new machines each cycle found",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short", "label": "Cycles /  min" }
   ],
   "targets": [
    {
     "expr": "increase(choria_provisioner_discover_cycles{site=~\"${instance}\"}[1m])",
     "legendFormat": "Discovery Run"
    },
    {
     "expr": "increase(choria_provisioner_discovered{site=~\"${instance}\"}[1m])",
     "legendFormat": "Discovered"
    }
   ]
  },
  {
   "title": "Events Processed",
   "type": "graph",
   "description": "How many nodes were discovered due to events being fired about them",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 5 },
   "yaxes": [
    { "format": "short", "label": "nodes / minute" }
   ],
   "targets": [
    {
     "expr": "increase(choria_provisioner_event_discovered{site=~\"${instance}\"}[1m])",
     "legendFormat": "Events"
    }
   ]
  },
  {
   "title": "RPC and Helper Times",
   "type": "graph",
   "description": "How long RPC requests and helper invocation takes",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "s", "label": "time" }
   ],
   "targets": [
    {
     "expr": "sum(rate(choria_provisioner_rpc_time_sum{site=~\"${instance}\"}[1m])) by (rpc) / sum(rate(choria_provisioner_rpc_time_count{site=~\"${instance}\"}[1m])) by (rpc)",
     "legendFormat": "{{rpc}}"
    },
    {
     "expr": "sum(rate(choria_provisioner_helper_time_sum{site=~\"${instance}\"}[1m])) by (rpc) / sum(rate(choria_provisioner_helper_time_count{site=~\"${instance}\"}[1m])) by (rpc)",
     "legendFormat": "helper"
    }
   ]
  },
  {
   "title": "Busy Workers",
   "type": "graph",
   "description": "How many workers are busy deploying nodes",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(choria_provisioner_busy_workers{site=~\"${instance}\"})",
     "legendFormat": "Workers"
    }
   ]
  },
  { "title": "Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Errors",
   "type": "graph",
   "description": "Various error states",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short", "label": "Errors" }
   ],
   "targets": [
    {
     "expr": "increase(choria_provisioner_rpc_errors{site=~\"${instance}\"}[5m])",
     "legendFormat": "RPC"
    },
    {
     "expr": "increase(choria_provisioner_helper_errors{site=~\"${instance}\"}[1m])",
     "legendFormat": "Helper"
    },
    {
     "expr": "increase(choria_provisioner_discovery_errors{site=~\"${instance}\"}[1m])",
     "legendFormat": "Discovery"
    },
    {
     "expr": "increase(choria_provisioner_provision_errors{site=~\"${instance}\"}[1m])",
     "legendFormat": "Provision"
    }
   ]
  }
 ]
}