FROM almalinux:8

ARG DATE="unknown"

WORKDIR /etc/choria-provisioner/

COPY choria-provisioner-0.99.0.${DATE}-1.el8.x86_64.rpm /tmp


RUN yum -y install ruby nc procps-ng openssl && \
    yum -y localinstall /tmp/choria-provisioner-0.99.0.${DATE}-1.el8.x86_64.rpm && \
    yum -y clean all

RUN groupadd --gid 2048 choria && \
    useradd -c "Choria Orchestrator - choria.io" -m --uid 2048 --gid 2048 choria && \
    chown -R choria:choria /etc/choria-provisioner

USER choria
ENV USER=choria

ENTRYPOINT ["/usr/sbin/choria-provisioner"]

CMD ["run", "--config=/etc/choria-provisioner/choria-provisioner.yaml", "--choria-config=/etc/choria-provisioner/client.cfg"]
