flags_map:
  Version: github.com/choria-io/provisioner/config.Version
  SHA: github.com/choria-io/provisioner/cmd.sha

foss:
  compile_targets:
    defaults:
      output: choria-provisioner-{{version}}-{{os}}-{{arch}}
      environment:
        CGO_ENABLED: "0"

    64bit_linux:
      os: linux
      arch: amd64

    32bit_linux:
      os: linux
      arch: 386

    darwin:
      os: darwin
      arch: amd64

  packages:
    defaults:
      name: choria-provisioner
      bindir: /usr/sbin
      etcdir: /etc/choria-provisioner
      release: 1
      manage_conf: 1

    el7_64:
      dist: el7
      template: el/el7
      target_arch: x86_64
      binary: 64bit_linux

    el8_64:
      dist: el8
      template: el/el8
      target_arch: x86_64
      binary: 64bit_linux
